export enum PaymentProcess {
    NO_PAYMENT_EXISTS = "NO_PAYMENT_EXISTS",
    OPEN_PAYMENT = "OPEN_PAYMENT",
    DURING_PAYMENT = "DURING_PAYMENT",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PAYMENT_FAILED = "PAYMENT_FAILED",
}